# Keep transport, storage, and platform APIs out of domain/application targets.
file(GLOB_RECURSE DOMAIN_FILES "${SOURCE_DIR}/backend/domain/*.h" "${SOURCE_DIR}/backend/domain/*.cpp")
foreach(PATH IN LISTS DOMAIN_FILES)
    file(READ "${PATH}" CONTENT)
    if(CONTENT MATCHES "#include [<\"][^\n]*(QJson|QSql|QNetwork|QMedia|QAudio|storage/|infrastructure/|ipc/|application/)")
        message(FATAL_ERROR "Domain dependency violation: ${PATH}")
    endif()
endforeach()
file(GLOB_RECURSE APPLICATION_FILES "${SOURCE_DIR}/backend/application/*.h" "${SOURCE_DIR}/backend/application/*.cpp" "${SOURCE_DIR}/backend/core/*.h" "${SOURCE_DIR}/backend/core/*.cpp")
foreach(PATH IN LISTS APPLICATION_FILES)
    file(READ "${PATH}" CONTENT)
    if(CONTENT MATCHES "#include [<\"][^\n]*(QJson|QSql|QNetwork|QMedia|QAudio|storage/|infrastructure/|ipc/|kugou/)")
        message(FATAL_ERROR "Application dependency violation: ${PATH}")
    endif()
endforeach()
file(GLOB_RECURSE IPC_FILES "${SOURCE_DIR}/backend/ipc/*.h" "${SOURCE_DIR}/backend/ipc/*.cpp")
foreach(PATH IN LISTS IPC_FILES)
    file(READ "${PATH}" CONTENT)
    if(CONTENT MATCHES "#include [<\"][^\n]*(QSql|QMedia|QAudio|storage/|infrastructure/|kugou/)")
        message(FATAL_ERROR "IPC dependency violation: ${PATH}")
    endif()
endforeach()
file(GLOB_RECURSE FRONTEND_FILES "${SOURCE_DIR}/frontend/qt-qml/src/controllers/*.h" "${SOURCE_DIR}/frontend/qt-qml/src/controllers/*.cpp")
foreach(PATH IN LISTS FRONTEND_FILES)
    file(READ "${PATH}" CONTENT)
    if(CONTENT MATCHES "#include [<\"][^\n]*(backend/|storage/|core/player|QSql|QMedia|QAudio)")
        message(FATAL_ERROR "Frontend dependency violation: ${PATH}")
    endif()
endforeach()
