set(NEKOTUNE_NODE_VERSION "24.21.0")
set(NEKOTUNE_NODE_SHA256 "fd8e59d5a511510f6a298afb548f18c7d2b1be404d8b4a27d94fbe49f56cb2d6")
set(NEKOTUNE_NODE_ARCHIVE "" CACHE FILEPATH "Offline node-v24.21.0-linux-x64.tar.xz archive")
if(NOT CMAKE_SYSTEM_NAME STREQUAL "Linux" OR NOT CMAKE_SYSTEM_PROCESSOR MATCHES "x86_64|AMD64")
    message(FATAL_ERROR "Bundled extension runtime currently supports Linux x86_64")
endif()
set(NEKOTUNE_RUNTIME_DIR "${CMAKE_BINARY_DIR}/extensions-runtime")
file(MAKE_DIRECTORY "${NEKOTUNE_RUNTIME_DIR}")
if(NOT NEKOTUNE_NODE_ARCHIVE)
    set(NEKOTUNE_NODE_ARCHIVE "${NEKOTUNE_RUNTIME_DIR}/node-v${NEKOTUNE_NODE_VERSION}-linux-x64.tar.xz")
    if(NOT EXISTS "${NEKOTUNE_NODE_ARCHIVE}")
        file(DOWNLOAD "https://nodejs.org/dist/v${NEKOTUNE_NODE_VERSION}/node-v${NEKOTUNE_NODE_VERSION}-linux-x64.tar.xz"
             "${NEKOTUNE_NODE_ARCHIVE}" EXPECTED_HASH "SHA256=${NEKOTUNE_NODE_SHA256}" TLS_VERIFY ON STATUS NODE_DOWNLOAD TIMEOUT 180)
        list(GET NODE_DOWNLOAD 0 NODE_DOWNLOAD_CODE)
        if(NOT NODE_DOWNLOAD_CODE EQUAL 0)
            file(REMOVE "${NEKOTUNE_NODE_ARCHIVE}")
            message(FATAL_ERROR "Node runtime download failed: ${NODE_DOWNLOAD}. Supply NEKOTUNE_NODE_ARCHIVE for offline builds.")
        endif()
    endif()
endif()
file(SHA256 "${NEKOTUNE_NODE_ARCHIVE}" NODE_ARCHIVE_HASH)
if(NOT NODE_ARCHIVE_HASH STREQUAL NEKOTUNE_NODE_SHA256)
    message(FATAL_ERROR "Bundled Node archive SHA256 mismatch")
endif()
if(NOT EXISTS "${NEKOTUNE_RUNTIME_DIR}/node-v${NEKOTUNE_NODE_VERSION}-linux-x64/bin/node")
    file(ARCHIVE_EXTRACT INPUT "${NEKOTUNE_NODE_ARCHIVE}" DESTINATION "${NEKOTUNE_RUNTIME_DIR}")
endif()
set(NEKOTUNE_NODE_BINARY "${NEKOTUNE_RUNTIME_DIR}/node-v${NEKOTUNE_NODE_VERSION}-linux-x64/bin/node")
find_program(PNPM_EXECUTABLE pnpm REQUIRED)
file(GLOB_RECURSE EXTENSION_RUNTIME_SOURCES CONFIGURE_DEPENDS "${CMAKE_SOURCE_DIR}/extensions/runtime/*.mjs" "${CMAKE_SOURCE_DIR}/extensions/sdk/*.ts" "${CMAKE_SOURCE_DIR}/extensions/examples/*.ts")
file(GLOB_RECURSE BUNDLED_EXTENSION_SOURCES CONFIGURE_DEPENDS "${CMAKE_SOURCE_DIR}/extensions/builtin/*")
add_custom_command(OUTPUT "${CMAKE_SOURCE_DIR}/extensions/dist/supervisor.cjs" "${CMAKE_SOURCE_DIR}/extensions/dist/worker.cjs" "${CMAKE_SOURCE_DIR}/extensions/dist/builtin/nekotune.kugou.zip"
    COMMAND "${CMAKE_COMMAND}" -E env CI=true "${PNPM_EXECUTABLE}" install --frozen-lockfile --store-dir "${CMAKE_BINARY_DIR}/pnpm-store"
    COMMAND "${PNPM_EXECUTABLE}" build
    WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}/extensions"
    DEPENDS ${EXTENSION_RUNTIME_SOURCES} ${BUNDLED_EXTENSION_SOURCES} "${CMAKE_SOURCE_DIR}/extensions/tools/build.mjs" "${CMAKE_SOURCE_DIR}/extensions/tools/cli.mjs" "${CMAKE_SOURCE_DIR}/extensions/package.json" "${CMAKE_SOURCE_DIR}/extensions/pnpm-lock.yaml" "${CMAKE_SOURCE_DIR}/extensions/pnpm-workspace.yaml"
    VERBATIM)
add_custom_target(nekotune_extension_runtime ALL DEPENDS "${CMAKE_SOURCE_DIR}/extensions/dist/supervisor.cjs" "${CMAKE_SOURCE_DIR}/extensions/dist/worker.cjs" "${CMAKE_SOURCE_DIR}/extensions/dist/builtin/nekotune.kugou.zip")
include(GNUInstallDirs)
install(PROGRAMS "${NEKOTUNE_NODE_BINARY}" DESTINATION "${CMAKE_INSTALL_LIBEXECDIR}/nekotune" RENAME node)
install(FILES "${NEKOTUNE_RUNTIME_DIR}/node-v${NEKOTUNE_NODE_VERSION}-linux-x64/LICENSE" DESTINATION "${CMAKE_INSTALL_LIBEXECDIR}/nekotune" RENAME NODE-LICENSE)
install(DIRECTORY "${CMAKE_SOURCE_DIR}/extensions/dist/" DESTINATION "${CMAKE_INSTALL_LIBEXECDIR}/nekotune")
